#!/bin/sh
xrandr --auto                                                                                                                                                                              .
xrandr --output LVDS1 --right-of VGA1   
nitrogen --save --set-zoom-fill ~/.local/share/wallpaper.png
