#!/bin/sh
xrandr --auto
#xrandr --output LVDS1 --right-of VGA1   

if xrandr | grep -q "HDMI2 connected"; then
  #xrandr --output LVDS1 --off --right-of HDMI2 --output HDMI2 --auto --primary
  xrandr --output LVDS1 --primary --auto --right-of HDMI2 --output HDMI2 --auto
fi

#xrandr --output LVDS1 --right-of HDMI2   
nitrogen --save --set-zoom-fill ~/.local/share/wallpaper.png
