#!/bin/sh
xrandr --auto
#xrandr --output LVDS1 --right-of VGA1   
#xrandr --output LVDS1 --primary --auto --right-of HDMI2 --output HDMI2 --auto
xrandr --output LVDS1 --right-of HDMI2   
nitrogen --save --set-zoom-fill ~/.local/share/wallpaper.png
